groups:
- name: fraud_detection_alerts
  rules:
  - alert: HighFraudRate
    expr: rate(fraud_alerts_total[5m]) > 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High fraud alert rate detected
      description: Fraud alert rate is {{ $value }} per minute

  - alert: ModelLatencyHigh
    expr: histogram_quantile(0.95, rate(model_prediction_latency_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Model prediction latency is high
      description: 95th percentile latency is {{ $value }}s

  - alert: DataDrift
    expr: abs(feature_drift_score) > 0.3
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: Significant data drift detected
      description: Feature drift score is {{ $value }}

  - alert: HighErrorRate
    expr: rate(api_error_total[5m]) / rate(api_requests_total[5m]) > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High API error rate
      description: Error rate is {{ $value }}